INSERT INTO comment(comment, type) VALUES ('웃는 모습이 참 보기 좋아',0);
INSERT INTO comment(comment, type) VALUES ('긍정적인 분위기를 계속 유지하자',0);
INSERT INTO comment(comment, type) VALUES ('그 행복이 당신에게 어울려요',0);
INSERT INTO comment(comment, type) VALUES ('기분이 좋아보여서 다행이야!',0);
INSERT INTO comment(comment, type) VALUES ('당신은 오늘 환하게 웃고 있어요, 정말 좋아요!',0);
INSERT INTO comment(comment, type) VALUES ('세계 최고의 기분이죠?',0);
INSERT INTO comment(comment, type) VALUES ('빛나는 오늘 하루',0);
INSERT INTO comment(comment, type) VALUES ('내일도 행복의 열차를 계속 운행해볼까?',0);
INSERT INTO comment(comment, type) VALUES ('즐거운 시간을 보냈구나!',0);
INSERT INTO comment(comment, type) VALUES ('이 행복을 조금이라도 즐길 수 있길',0);
INSERT INTO comment(comment, type) VALUES ('그 미소를 계속 유지하세요!',0);
INSERT INTO comment(comment, type) VALUES ('걸어다니는 행복공장',0);
INSERT INTO comment(comment, type) VALUES ('지금 당장은 무엇이든 정복할 수 있을 것 같은 느낌',0);
INSERT INTO comment(comment, type) VALUES ('당신이 하는 모든 일에서 그 행복이 빛나도록 하세요',0);
INSERT INTO comment(comment, type) VALUES ('이 멋진 느낌의 매 순간을 만끽하세요!',0);
INSERT INTO comment(comment, type) VALUES ('당신을 막을 수 없어요!',0);
INSERT INTO comment(comment, type) VALUES ('열정은 불보다 더 격렬하다',0);
INSERT INTO comment(comment, type) VALUES ('용기 있는 자는 스스로 운을 만들어간다.',0);
INSERT INTO comment(comment, type) VALUES ('자신의 가치를 진심으로 믿는 자',0);
INSERT INTO comment(comment, type) VALUES ('실패가 두려워 시도조차 하지 않는 것이야말로 무능력한 것이다.',0);
INSERT INTO comment(comment, type) VALUES ('상황에 관계없이 누구나 스스로가 만든 세상을 살아간다.',0);
INSERT INTO comment(comment, type) VALUES ('경험은 훌룽한 선생이다.',0);
INSERT INTO comment(comment, type) VALUES ('자기 자신을 희생하는 것처럼 행복한 일은 없다.',0);
INSERT INTO comment(comment, type) VALUES ('성공이란 열정을 잃지 않고 실패를 거듭할 수 있는 능력이다.',0);
INSERT INTO comment(comment, type) VALUES ('웃는 얼굴에 침 못 뱉는다.',0);
INSERT INTO comment(comment, type) VALUES ('당당하게 일어서!',0);
INSERT INTO comment(comment, type) VALUES ('자신을 굳게 믿는 힘보다 대단한 것은 없다.',0);
INSERT INTO comment(comment, type) VALUES ('성공은 시도하는 용기에서 시작됩니다.',0);
INSERT INTO comment(comment, type) VALUES ('힘은 계속해서 나아가려는 의지로부터',0);
INSERT INTO comment(comment, type) VALUES ('결단력은 잠재력을 발휘하는 열쇠',0);
INSERT INTO comment(comment, type) VALUES ('오늘 하루도 최고야!',0);
INSERT INTO comment(comment, type) VALUES ('긍정의 물결을 함께 타자',0);
INSERT INTO comment(comment, type) VALUES ('미소가 방을 환하게 밝혀주고 있어',0);
INSERT INTO comment(comment, type) VALUES ('매일매일을 오늘처럼 즐겁게 보내자.',0);
INSERT INTO comment(comment, type) VALUES ('이 행복한 순간을 계속 소중히 간직하세요',0);
INSERT INTO comment(comment, type) VALUES ('너의 행복은 주변 사람들에게 선물이야',0);
INSERT INTO comment(comment, type) VALUES ('너의 미소는 마치 신선한 공기를 마시는 것 같아. 너무 상쾌해!',0);
INSERT INTO comment(comment, type) VALUES ('긍정적인 에너지를 계속해서 흐르게 해줘',0);
INSERT INTO comment(comment, type) VALUES ('음식을 먹을 때 한 입을 먹고 눈을 감고 음식을 즐겨라',0);
INSERT INTO comment(comment, type) VALUES ('당신이 변화했다면 다른 것들은 따라올 것이다.',0);
INSERT INTO comment(comment, type) VALUES ('수 많은 별들도 기분 좋은 날',0);
INSERT INTO comment(comment, type) VALUES ('순간을 사랑하라. 그러면 그 순간의 에너지가 모든 경계를 넘어 퍼져나갈 것이다.',0);
INSERT INTO comment(comment, type) VALUES ('상대의 급소를 공략하면 마음도 사로잡을 수 있다.',0);
INSERT INTO comment(comment, type) VALUES ('뭘 해도 되는 날',0);
INSERT INTO comment(comment, type) VALUES ('오늘의 MVP는 당신!',0);
INSERT INTO comment(comment, type) VALUES ('우리는 행복하기 때문에 웃는 게 아니라, 웃기 때문에 행복하다.',0);
INSERT INTO comment(comment, type) VALUES ('웃는 자에게 복이 온다.',0);
INSERT INTO comment(comment, type) VALUES ('피할 수 없으면 즐겨라!',0);
INSERT INTO comment(comment, type) VALUES ('행복은 습관이다.',0);
INSERT INTO comment(comment, type) VALUES ('너의 운명의 별은 너의 마음 속에 있다.',0);
INSERT INTO comment(comment, type) VALUES ('인생에서 중요한 것은 그저 존재하는 것이 아닌 느끼는 것',1);
INSERT INTO comment(comment, type) VALUES ('인생에서 중요한 것은 그저 숨쉬는 것이 아닌 생각하는 것이다.',1);
INSERT INTO comment(comment, type) VALUES ('인생에서 최고의 순간은 있는 힘껏 노력한 뒤에 갖는 휴식이다.',1);
INSERT INTO comment(comment, type) VALUES ('상황에 관계없이 누구나 스스로가 만든 세상을 살아간다.',1);
INSERT INTO comment(comment, type) VALUES ('너의 온화한 긍정이 변화를 만들어',1);
INSERT INTO comment(comment, type) VALUES ('평화로운 분위기의 소유자',1);
INSERT INTO comment(comment, type) VALUES ('항상 편안한 미소로 있어줘서 고마워',1);
INSERT INTO comment(comment, type) VALUES ('당신은 주변 사람들에게 많은 기쁨과 평화를 가져다줘요',1);
INSERT INTO comment(comment, type) VALUES ('고독함 속에서 강한 자는 성장한다.',1);
INSERT INTO comment(comment, type) VALUES ('수고했어 오늘도',1);
INSERT INTO comment(comment, type) VALUES ('인간의 행복은 얼마나 홀로 잘 견딜 수 있는가에 달렸다.',1);
INSERT INTO comment(comment, type) VALUES ('쾌락에 지쳤을 때 고독은 얼마나 반갑고 고마운가',1);
INSERT INTO comment(comment, type) VALUES ('희망은 불가능한 것을 성취하게 한다.',1);
INSERT INTO comment(comment, type) VALUES ('내일은 내일의 태양이 뜬다',1);
INSERT INTO comment(comment, type) VALUES ('거부는 해도 포기는 하지 않는다.',1);
INSERT INTO comment(comment, type) VALUES ('우표는 어딘가에 도착할 때까지 어떤 한 곳에 들러붙어 있다.',1);
INSERT INTO comment(comment, type) VALUES ('행복의 비결은 포기할 것을 포기하는 것이다.',1);
INSERT INTO comment(comment, type) VALUES ('꿈을 실현하는 것이 나의 목표이다.',1);
INSERT INTO comment(comment, type) VALUES ('자기 자신을 믿을 때 성공의 첫번째 비결을 갖게 되는 것이다.',1);
INSERT INTO comment(comment, type) VALUES ('삶이 소중한 것을 알기에 지금 이 순간이 행복한 것',1);
INSERT INTO comment(comment, type) VALUES ('행복이란 내가 가진 것을 즐기는 것',1);
INSERT INTO comment(comment, type) VALUES ('어제의 나보다 더 나아진 오늘',1);
INSERT INTO comment(comment, type) VALUES ('희망만 있으면 행복의 싹은 그곳에서 움튼다.',1);
INSERT INTO comment(comment, type) VALUES ('모자라는 부분을 채워가는 것이 행복이다.',1);
INSERT INTO comment(comment, type) VALUES ('가장 적은 것으로도 만족하는 사람이 가장 부유한 사람이다.',1);
INSERT INTO comment(comment, type) VALUES ('자기 신뢰는 성공의 첫 번째 비결이다.',1);
INSERT INTO comment(comment, type) VALUES ('최대한의 삶을 살고, 최대한 긍정적인 것에 집중하자',1);
INSERT INTO comment(comment, type) VALUES ('무엇이건 최선을 다해라. 모두들 그것을 좋아할 것이다.',1);
INSERT INTO comment(comment, type) VALUES ('미래를 위하여 오늘을 즐기며 살자',1);
INSERT INTO comment(comment, type) VALUES ('가슴 뛰는 상상을 즐겨라',1);
INSERT INTO comment(comment, type) VALUES ('때가 되면 뭘해야 할지 다 알게 될테니까',1);
INSERT INTO comment(comment, type) VALUES ('낙관적인 사람은 고난에서 기회를 본다',1);
INSERT INTO comment(comment, type) VALUES ('뒤로 살짝 물러서면 큰 문제도 작게 보인다.',1);
INSERT INTO comment(comment, type) VALUES ('나 자신에 대한 자신감을 잃으면 온 세상이 나의 적이 된다.',1);
INSERT INTO comment(comment, type) VALUES ('날마다 진보하지 않으면 날마다 퇴보한다.',1);
INSERT INTO comment(comment, type) VALUES ('오늘은 야식 어때?',1);
INSERT INTO comment(comment, type) VALUES ('좋은 생각이 났어. 니 생각',1);
INSERT INTO comment(comment, type) VALUES ('우리 모두 꽤나 괜찮은 존재이다.',1);
INSERT INTO comment(comment, type) VALUES ('인내하는 자는 누구든지 유종의 미를 거두리라',1);
INSERT INTO comment(comment, type) VALUES ('집을 가장 아름답게 꾸며주는 것은 자주 찾아오는 친구들이다.',1);
INSERT INTO comment(comment, type) VALUES ('일단 한 번 해보는 것이다',1);
INSERT INTO comment(comment, type) VALUES ('오늘이 제일 중요하다',1);
INSERT INTO comment(comment, type) VALUES ('마음을 내려놓고 살자',1);
INSERT INTO comment(comment, type) VALUES ('감사하는 마음은 자신에게 주는 선물',1);
INSERT INTO comment(comment, type) VALUES ('한 만큼 되돌아오는 게 인생이다',1);
INSERT INTO comment(comment, type) VALUES ('용감한 마음은 불은을 끊어버린다.',1);
INSERT INTO comment(comment, type) VALUES ('친구를 가지는 유일한 길은 친구가 되는 것이다.',1);
INSERT INTO comment(comment, type) VALUES ('살아야 할 이유가 있는 사람은 거의 모든 일을 견딜 수 있다.',1);
INSERT INTO comment(comment, type) VALUES ('한 알의 모래에서 세상을 보고 한 송이 들꽃에서 천국을 본다',1);
INSERT INTO comment(comment, type) VALUES ('하루를 마치면 거기서 끝내라',1);
INSERT INTO comment(comment, type) VALUES ('살아남은 종은 가장 강하거나 가장 영리한 종이 아니라 변화에 가장 잘 적응하는 종이다.',2);
INSERT INTO comment(comment, type) VALUES ('실패로부터 성공을 배워라',2);
INSERT INTO comment(comment, type) VALUES ('좌절과 실패는 성공으로 가는 두 가지의 가장 확실한 디딤돌이다.',2);
INSERT INTO comment(comment, type) VALUES ('전사 정신으로 역경에 맞서 더욱 강해진다.',2);
INSERT INTO comment(comment, type) VALUES ('인내는 성공으로 가는 다리이다.',2);
INSERT INTO comment(comment, type) VALUES ('실패했다고 해서 스스로를 괴롭히지 마라.',2);
INSERT INTO comment(comment, type) VALUES ('성공은 실패의 맨 끝에 있다.',2);
INSERT INTO comment(comment, type) VALUES ('성실한 마음으로 물리칠 수 없는 고난은 없다.',2);
INSERT INTO comment(comment, type) VALUES ('모든 답을 바로 알 수 없어도 괜찮아',2);
INSERT INTO comment(comment, type) VALUES ('최선을 다하고 있구나!',2);
INSERT INTO comment(comment, type) VALUES ('한발 물러서서 한숨 돌리셔도 괜찮아요',2);
INSERT INTO comment(comment, type) VALUES ('이렇게 힘든 경험을 하게 해서 미안해요',2);
INSERT INTO comment(comment, type) VALUES ('힘든 시기는 영원히 지속되지 않아. 앞으로 더 밝은 날이 올거야',2);
INSERT INTO comment(comment, type) VALUES ('가장 어두운 순간에도 빛으로 향하는 길은 있다.',2);
INSERT INTO comment(comment, type) VALUES ('재충전을 위한 휴식은 필수',2);
INSERT INTO comment(comment, type) VALUES ('남들 보기에 내가 어떻든 내 행복이 우선이니까 신경 쓰지 말라고',2);
INSERT INTO comment(comment, type) VALUES ('내일은 오늘보다 더 괜찮을거야',2);
INSERT INTO comment(comment, type) VALUES ('최선이 안되면 차선이 있고, 차선이 안 되면 차차선도 있는 법이거든',2);
INSERT INTO comment(comment, type) VALUES ('"비 온 뒤 맑음"',2);
INSERT INTO comment(comment, type) VALUES ('매일매일이 다른데 어떻게 기분 좋고 내용 알차고 그러기만 하겠어요',2);
INSERT INTO comment(comment, type) VALUES ('지금 하는 것이 중요하고 지금의 나를 변화시킨다.',2);
INSERT INTO comment(comment, type) VALUES ('반복에 지치지 않는 자가 성취한다.',2);
INSERT INTO comment(comment, type) VALUES ('느리다고, 조금 늦었다고 모자란 법은 없기에',2);
INSERT INTO comment(comment, type) VALUES ('이 세상에 위대한 사람은 없다. 단지 평범한 사람들이 일어나 맞서는 위대한 도전이 있을 뿐이다.',2);
INSERT INTO comment(comment, type) VALUES ('힘들고 지쳤다는 건 노력했다는 증거',2);
INSERT INTO comment(comment, type) VALUES ('슬럼프가 왔다는 건 열정적이었다는 증거',2);
INSERT INTO comment(comment, type) VALUES ('실패했다는 건 도전했다는 증거',2);
INSERT INTO comment(comment, type) VALUES ('긴장된다는 건 그 만큼 진심의 증거',2);
INSERT INTO comment(comment, type) VALUES ('그만둘까는 건 지금까지 희망을 버리지 않고 있던 증거',2);
INSERT INTO comment(comment, type) VALUES ('언젠가 반드시 비는 그치고, 구름 사이로 파란 하늘이 엿보인다.',2);
INSERT INTO comment(comment, type) VALUES ('영원히 지는 일은 없다.',2);
INSERT INTO comment(comment, type) VALUES ('고통이 지속되는 일은 없다.',2);
INSERT INTO comment(comment, type) VALUES ('당신은 당신의 시간대에 있는 것 뿐입니다.',2);
INSERT INTO comment(comment, type) VALUES ('흔들리지 않고 피는 꽃은 없다고 했다.',2);
INSERT INTO comment(comment, type) VALUES ('당신은 반드시 행복해질 사람이다.',2);
INSERT INTO comment(comment, type) VALUES ('온 힘을 다했잖아. 다 잘될거야.',2);
INSERT INTO comment(comment, type) VALUES ('네가 겪는 숱한 저항과 매서운 바람들은 네 잘못이 아니란다.',2);
INSERT INTO comment(comment, type) VALUES ('꿈이 없을 수도 있어요. 행복하시면 됩니다.',2);
INSERT INTO comment(comment, type) VALUES ('남을 위해 사는 착한 사람 말고 나를 위해 사는 좋은 사람이 되기를',2);
INSERT INTO comment(comment, type) VALUES ('최선을 다했으면, 최고가 아니어도 괜찮아.',2);
INSERT INTO comment(comment, type) VALUES ('누가 결승전까지 가는 길에 예쁜 것을 많이 보느냐',2);
INSERT INTO comment(comment, type) VALUES ('걱정은 걱정을 낳고, 고민도 다른 고민을 낳는다.',2);
INSERT INTO comment(comment, type) VALUES ('아무런 가능성이 없었다면 처음부터 시작하지도 않았을 거야.',2);
INSERT INTO comment(comment, type) VALUES ('걱정 마. 그렇게 큰 일은 아니야.',2);
INSERT INTO comment(comment, type) VALUES ('누구나 미완성으로 시작한다.',2);
INSERT INTO comment(comment, type) VALUES ('모든 경험은 그 자체로 성공이다.',2);
INSERT INTO comment(comment, type) VALUES ('당신이 걷는 모든 길의 이름은 성장입니다.',2);
INSERT INTO comment(comment, type) VALUES ('지나고 나면 다 괜찮아진대',2);
INSERT INTO comment(comment, type) VALUES ('울어도 돼, 괜찮아.',2);
INSERT INTO comment(comment, type) VALUES ('누구보다 가장 잘하고 싶었던 나의 마음이 담긴 오늘을 미워하지 마세요.',2);
INSERT INTO comment(comment, type) VALUES ('가만히 있다고 해서 좋은 결과를 얻는 것은 아니다.',3);
INSERT INTO comment(comment, type) VALUES ('교차로에서는 어느 쪽으로 갈지 빨리 결정을 내려야 한다.',3);
INSERT INTO comment(comment, type) VALUES ('실패로부터 성공을 배워라',3);
INSERT INTO comment(comment, type) VALUES ('좌절과 실패는 성공으로 가는 두 가지의 가장 확실한 디딤돌이다.',3);
INSERT INTO comment(comment, type) VALUES ('실패했다고 해서 스스로를 괴롭히지 마라.',3);
INSERT INTO comment(comment, type) VALUES ('성공은 실패의 맨 끝에 있다.',3);
INSERT INTO comment(comment, type) VALUES ('성실한 마음으로 물리칠 수 없는 고난은 없다.',3);
INSERT INTO comment(comment, type) VALUES ('인내는 성공으로 가는 다리이다.',3);
INSERT INTO comment(comment, type) VALUES ('희망은 삶 속에 존재하는 가장 위대한 힘이며, 죽음을 물리칠 수 있는 유일한 무기이다.',3);
INSERT INTO comment(comment, type) VALUES ('내일은 내일의 태양이 뜬다.',3);
INSERT INTO comment(comment, type) VALUES ('걱정마',3);
INSERT INTO comment(comment, type) VALUES ('수고했어 오늘도',3);
INSERT INTO comment(comment, type) VALUES ('인간의 행복은 얼마나 홀로 잘 견딜 수 있는가에 달렸다.',3);
INSERT INTO comment(comment, type) VALUES ('쾌락에 지쳤을 때 고독은 얼마나 반갑고 고마운가',3);
INSERT INTO comment(comment, type) VALUES ('희망은 불가능한 것을 성취하게 한다.',3);
INSERT INTO comment(comment, type) VALUES ('고독함 속에서 강한 자는 성장한다.',3);
INSERT INTO comment(comment, type) VALUES ('거부는 해도 포기는 하지 않는다.',3);
INSERT INTO comment(comment, type) VALUES ('우표는 어딘가에 도착할 때까지 어떤 한 곳에 들러붙어 있다.',3);
INSERT INTO comment(comment, type) VALUES ('행복의 비결은 포기할 것을 포기하는 것이다.',3);
INSERT INTO comment(comment, type) VALUES ('해결책이 없다면 걱정해도 소용없는 일이다.',3);
INSERT INTO comment(comment, type) VALUES ('과거는 이미 존재하지 않고, 미래는 아직 닥치지 않았으며, 존재하는 것은 오직 현재뿐이다.',3);
INSERT INTO comment(comment, type) VALUES ('길을 잃는다는 것은 곧 새로운 길을 알게 된다는 뜻이다.',3);
INSERT INTO comment(comment, type) VALUES ('바보는 방황하고 현명한 사람은 여행을 떠난다.',3);
INSERT INTO comment(comment, type) VALUES ('길이 막혔다면 원점으로 돌아가라',3);
INSERT INTO comment(comment, type) VALUES ('초심으로 돌아가는 것이 뜻밖에 색다른 발견을 가져다줄 수도 있다.',3);
INSERT INTO comment(comment, type) VALUES ('태어난 모든 것들은 기약조차 없는 이별을 준비하고 있어야 한다.',3);
INSERT INTO comment(comment, type) VALUES ('사랑을 잃었을 때 치료법은 더욱 사랑하는 것밖에 없다.',3);
INSERT INTO comment(comment, type) VALUES ('어깨에 진 짐이야말로 인간의 목표를 달성시키는 데 도움이 될 것이다.',3);
INSERT INTO comment(comment, type) VALUES ('무슨 일이 있어도 나는 여기에 있어.',3);
INSERT INTO comment(comment, type) VALUES ('느껴야 할 것을 느껴보는 데 시간을 투자해보자',3);
INSERT INTO comment(comment, type) VALUES ('가끔은 괜찮지 않아도 괜찮아요',3);
INSERT INTO comment(comment, type) VALUES ('나는 듣기 위해 여기에 있어요',3);
INSERT INTO comment(comment, type) VALUES ('너의 감정은 타당해',3);
INSERT INTO comment(comment, type) VALUES ('이런 일을 겪게 해서 미안해요',3);
INSERT INTO comment(comment, type) VALUES ('조금은 휴식을 가져도 괜찮아.',3);
INSERT INTO comment(comment, type) VALUES ('나는 이것을 극복할 너의 능력을 믿어',3);
INSERT INTO comment(comment, type) VALUES ('너가 느끼는 것을 그대로 느끼도록 냅두자.',3);
INSERT INTO comment(comment, type) VALUES ('너는 최선을 다하고 있고, 그걸로 충분해',3);
INSERT INTO comment(comment, type) VALUES ('많이 힘들었겠지, 고생했어',3);
INSERT INTO comment(comment, type) VALUES ('너는 가치 있고 행복할 자격이 있는 사람이야!',3);
INSERT INTO comment(comment, type) VALUES ('너는 너를 아는 것보다 더 강한 사람이야',3);
INSERT INTO comment(comment, type) VALUES ('오늘도 내일은 어제가 될 거야.',3);
INSERT INTO comment(comment, type) VALUES ('한 번에 한 단계씩 함께 나아가자',3);
INSERT INTO comment(comment, type) VALUES ('이런 감정에 맞서는 너의 용기에 감탄해!',3);
INSERT INTO comment(comment, type) VALUES ('지금 이 순간에 빠져있지 마, 더 밝은 날이 올거야.',3);
INSERT INTO comment(comment, type) VALUES ('너의 감정을 표현해도 괜찮아.',3);
INSERT INTO comment(comment, type) VALUES ('지금 모든 답을 얻지 못해도 괜찮아.',3);
INSERT INTO comment(comment, type) VALUES ('너의 회복력은 어마무시해!',3);
INSERT INTO comment(comment, type) VALUES ('가장 어두운 순간에도 앞으로 나아갈 길은 있어.',3);
INSERT INTO comment(comment, type) VALUES ('너는 사랑과 이해를 받을 자격이 있어.',3);
